name: CI
on: [push]
jobs:
  commit-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(feat|fix|docs|style|refactor|chore|perf|test|build|ci|revert)(\(\S+\))?: .+'
          error: "Invalid commit type"
          excludeDescription: "true"
          excludeTitle: "false"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  typo-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      
      - name: Typo Check
        uses: crate-ci/typos@v1.23.6
        with:
          config: ./.typo.toml

  format-check:
    runs-on: ubuntu-latest
    needs: [typo-check, commit-check]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install LLVM-18
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18

    - name: Install ninja build
      run: |
        sudo apt install ninja-build 

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-18 clang-tidy-18 clang-format-18

    - name: Prepare compile_commands.json
      run: |
        mkdir build && cd build &&CC=clang-18 CXX=clang++-18 cmake .. -G Ninja

    - name: run check
      run: |
          ./build_support/ci_script.sh
